// object containing all the different maps within game
window.OverworldMaps = {
  Demo: {
    id: "Demo",
    lowerSrc: "/db/images/maps/DemoLower.png", // path to image that we want to load
    upperSrc: "/db/images/maps/DemoUpper.png",
    configObjects: {
      hero: {
        type: "Person",
        x: utils.withGrid(5),
        y: utils.withGrid(6),
        isPlayerControlled: true,
      },
      regina: {
        type: "Person",
        x: utils.withGrid(7),
        y: utils.withGrid(9),
        src: "/db/images/characters/people/regina.png",
        behaviorLoop: [
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
        ],
        talking: [
          // each object is a scenario
          {
            required: ["TALKED_TO_MOUSE"], // this scenario only runs if required story flags are true. can have multiple.
            events: [
              {
                type: "textMessage",
                text: "Isn't Mouse the coolest?",
                faceHero: "regina",
              },
            ],
          },
          {
            events: [
              {
                type: "textMessage",
                text: "REGINA: I'm going to crush you!",
                faceHero: "regina",
              },
              { type: "battle", enemyId: "regina", locationId: "Demo" },
              { type: "addStoryFlag", flag: "DEFEATED_REGINA" }, // receive this story flag if battle is won
              { type: "textMessage", text: "REGINA: Hey that wasn't nice..." },
            ],
          },
        ],
      },
      mouse: {
        type: "Person",
        x: utils.withGrid(8),
        y: utils.withGrid(5),
        src: "/db/images/characters/people/mouse.png",
        behaviorLoop: [
          { type: "stand", direction: "down", time: 3000 },
          { type: "stand", direction: "left", time: 2000 },
          { type: "stand", direction: "down", time: 3000 },
          { type: "stand", direction: "right", time: 2000 },
        ],
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "MOUSE: Ahahaaaaaaa",
                faceHero: "mouse",
              },
              { type: "addStoryFlag", flag: "TALKED_TO_MOUSE" },
            ],
          },
        ],
      },
      pizzaStone: {
        type: "PizzaStone",
        x: utils.withGrid(2),
        y: utils.withGrid(7),
        storyFlag: "USED_PIZZA_STONE",
        pizzas: ["v001", "f001"], // can make it so that they have different options for crafting
      },
    },
    walls: {
      [utils.asGridCoord(7, 6)]: true,
      [utils.asGridCoord(8, 6)]: true,
      [utils.asGridCoord(7, 7)]: true,
      [utils.asGridCoord(8, 7)]: true,
      [utils.asGridCoord(1, 3)]: true,
      [utils.asGridCoord(2, 3)]: true,
      [utils.asGridCoord(3, 3)]: true,
      [utils.asGridCoord(4, 3)]: true,
      [utils.asGridCoord(5, 3)]: true,
      [utils.asGridCoord(7, 3)]: true,
      [utils.asGridCoord(6, 4)]: true,
      [utils.asGridCoord(8, 4)]: true,
      [utils.asGridCoord(9, 3)]: true,
      [utils.asGridCoord(10, 3)]: true,
      [utils.asGridCoord(0, 4)]: true,
      [utils.asGridCoord(0, 5)]: true,
      [utils.asGridCoord(0, 6)]: true,
      [utils.asGridCoord(0, 7)]: true,
      [utils.asGridCoord(0, 8)]: true,
      [utils.asGridCoord(0, 9)]: true,
      [utils.asGridCoord(11, 4)]: true,
      [utils.asGridCoord(11, 5)]: true,
      [utils.asGridCoord(11, 6)]: true,
      [utils.asGridCoord(11, 7)]: true,
      [utils.asGridCoord(11, 8)]: true,
      [utils.asGridCoord(11, 9)]: true,
      [utils.asGridCoord(11, 10)]: true,
      [utils.asGridCoord(1, 10)]: true,
      [utils.asGridCoord(2, 10)]: true,
      [utils.asGridCoord(3, 10)]: true,
      [utils.asGridCoord(4, 10)]: true,
      [utils.asGridCoord(6, 10)]: true,
      [utils.asGridCoord(7, 10)]: true,
      [utils.asGridCoord(8, 10)]: true,
      [utils.asGridCoord(9, 10)]: true,
      [utils.asGridCoord(10, 10)]: true,
    },
    cutsceneSpaces: {
      [utils.asGridCoord(7, 4)]: [
        {
          events: [
            { who: "mouse", type: "walk", direction: "left" },
            { who: "mouse", type: "stand", direction: "up", time: 500 },
            { type: "textMessage", text: "MOUSE: Hey, get outta there!" },
            { who: "mouse", type: "walk", direction: "right" },
            { who: "mouse", type: "stand", direction: "left", time: 500 },
            { who: "hero", type: "walk", direction: "down" },
            { who: "mouse", type: "stand", direction: "down" },
            { who: "hero", type: "walk", direction: "left" },
          ],
        },
      ],
      [utils.asGridCoord(5, 10)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "Demo",
              x: utils.withGrid(7),
              y: utils.withGrid(4),
              direction: "down",
            },
          ],
        },
      ],
    },
  },
  Street: {
    id: "Street",
    lowerSrc: "/db/images/maps/StreetLower.png",
    upperSrc: "/db/images/maps/StreetUpper.png",
    configObjects: {
      hero: {
        type: "Person",
        x: utils.withGrid(18),
        y: utils.withGrid(12),
        isPlayerControlled: true,
      },
      regina: {
        type: "Person",
        x: utils.withGrid(21),
        y: utils.withGrid(8),
        src: "/db/images/characters/people/regina.png",
        behaviorLoop: [
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
        ],
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "REGINA: Um.....hi?",
                faceHero: "regina",
              }
            ],
          },
        ],
      },
      johnny: {
        type: "Person",
        x: utils.withGrid(7),
        y: utils.withGrid(11),
        src: "/db/images/characters/people/johnny.png",
        behaviorLoop: [
          { type: "stand", direction: "down", time: 2000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "down", time: 2000 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" }
        ],
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "JOHNNY: Is there a bathroom around here?",
                faceHero: "johnny",
              }
            ],
          },
        ],
      },
    },
    walls: {
      [utils.asGridCoord(3, 10)]: true,
      [utils.asGridCoord(3, 11)]: true,
      [utils.asGridCoord(3, 12)]: true,
      [utils.asGridCoord(3, 13)]: true,
      [utils.asGridCoord(3, 14)]: true,
      [utils.asGridCoord(3, 15)]: true,
      [utils.asGridCoord(3, 16)]: true,
      [utils.asGridCoord(3, 17)]: true,
      [utils.asGridCoord(3, 18)]: true,
      [utils.asGridCoord(4, 19)]: true,
      [utils.asGridCoord(5, 19)]: true,
      [utils.asGridCoord(6, 19)]: true,
      [utils.asGridCoord(7, 19)]: true,
      [utils.asGridCoord(8, 19)]: true,
      [utils.asGridCoord(9, 19)]: true,
      [utils.asGridCoord(10, 19)]: true,
      [utils.asGridCoord(11, 19)]: true,
      [utils.asGridCoord(12, 19)]: true,
      [utils.asGridCoord(13, 19)]: true,
      [utils.asGridCoord(14, 19)]: true,
      [utils.asGridCoord(15, 19)]: true,
      [utils.asGridCoord(16, 19)]: true,
      [utils.asGridCoord(17, 19)]: true,
      [utils.asGridCoord(18, 19)]: true,
      [utils.asGridCoord(19, 19)]: true,
      [utils.asGridCoord(20, 19)]: true,
      [utils.asGridCoord(21, 19)]: true,
      [utils.asGridCoord(22, 19)]: true,
      [utils.asGridCoord(23, 19)]: true,
      [utils.asGridCoord(24, 19)]: true,
      [utils.asGridCoord(25, 19)]: true,
      [utils.asGridCoord(26, 19)]: true,
      [utils.asGridCoord(27, 19)]: true,
      [utils.asGridCoord(28, 19)]: true,
      [utils.asGridCoord(29, 19)]: true,
      [utils.asGridCoord(30, 19)]: true,
      [utils.asGridCoord(31, 19)]: true,
      [utils.asGridCoord(32, 19)]: true,
      [utils.asGridCoord(33, 19)]: true,
      [utils.asGridCoord(34, 18)]: true,
      [utils.asGridCoord(34, 17)]: true,
      [utils.asGridCoord(34, 16)]: true,
      [utils.asGridCoord(34, 15)]: true,
      [utils.asGridCoord(34, 14)]: true,
      [utils.asGridCoord(34, 13)]: true,
      [utils.asGridCoord(34, 12)]: true,
      [utils.asGridCoord(34, 11)]: true,
      [utils.asGridCoord(34, 10)]: true,
      [utils.asGridCoord(33, 9)]: true,
      [utils.asGridCoord(32, 9)]: true,
      [utils.asGridCoord(31, 9)]: true,
      [utils.asGridCoord(30, 9)]: true,
      [utils.asGridCoord(29, 8)]: true,
      [utils.asGridCoord(28, 9)]: true,
      [utils.asGridCoord(28, 8)]: true,
      [utils.asGridCoord(27, 7)]: true,
      [utils.asGridCoord(26, 7)]: true,
      [utils.asGridCoord(26, 6)]: true,
      [utils.asGridCoord(26, 5)]: true,
      [utils.asGridCoord(25, 4)]: true,
      [utils.asGridCoord(24, 5)]: true,
      [utils.asGridCoord(24, 6)]: true,
      [utils.asGridCoord(24, 7)]: true,
      [utils.asGridCoord(23, 7)]: true,
      [utils.asGridCoord(22, 7)]: true,
      [utils.asGridCoord(21, 7)]: true,
      [utils.asGridCoord(20, 7)]: true,
      [utils.asGridCoord(19, 7)]: true,
      [utils.asGridCoord(18, 7)]: true,
      [utils.asGridCoord(17, 7)]: true,
      [utils.asGridCoord(16, 7)]: true,
      [utils.asGridCoord(15, 7)]: true,
      [utils.asGridCoord(14, 8)]: true,
      [utils.asGridCoord(13, 8)]: true,
      [utils.asGridCoord(12, 9)]: true,
      [utils.asGridCoord(11, 9)]: true,
      [utils.asGridCoord(10, 9)]: true,
      [utils.asGridCoord(9, 9)]: true,
      [utils.asGridCoord(8, 9)]: true,
      [utils.asGridCoord(7, 9)]: true,
      [utils.asGridCoord(6, 9)]: true,
      [utils.asGridCoord(5, 8)]: true,
      [utils.asGridCoord(4, 9)]: true,
      [utils.asGridCoord(5, 14)]: true,
      [utils.asGridCoord(6, 14)]: true,
      [utils.asGridCoord(7, 14)]: true,
      [utils.asGridCoord(8, 14)]: true,
      [utils.asGridCoord(16, 11)]: true,
      [utils.asGridCoord(16, 10)]: true,
      [utils.asGridCoord(16, 9)]: true,
      [utils.asGridCoord(17, 11)]: true,
      [utils.asGridCoord(17, 10)]: true,
      [utils.asGridCoord(17, 9)]: true,
      [utils.asGridCoord(18, 11)]: true,
      [utils.asGridCoord(19, 11)]: true,
      [utils.asGridCoord(25, 11)]: true,
      [utils.asGridCoord(25, 10)]: true,
      [utils.asGridCoord(25, 9)]: true,
      [utils.asGridCoord(26, 11)]: true,
      [utils.asGridCoord(26, 10)]: true,
      [utils.asGridCoord(26, 9)]: true,
    },
    cutsceneSpaces: {
      [utils.asGridCoord(5, 9)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "Tony",
              x: utils.withGrid(6),
              y: utils.withGrid(12),
              direction: "up",
            },
          ],
        },
      ],
      [utils.asGridCoord(29, 9)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "Shop",
              x: utils.withGrid(5),
              y: utils.withGrid(12),
              direction: "up",
            },
          ],
        },
      ],
      [utils.asGridCoord(25, 5)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "North",
              x: utils.withGrid(7),
              y: utils.withGrid(16),
              direction: "up",
            },
          ],
        },
      ],
    },
  },
  Tony: {
    id: "Tony",
    lowerSrc: "/db/images/maps/DiningRoomLower.png",
    upperSrc: "/db/images/maps/DiningRoomUpper.png",
    configObjects: {
      hero: {
        type: "Person",
        isPlayerControlled: true,
        x: utils.withGrid(7),
        y: utils.withGrid(5),
      },
      chef: {
        type: "Person",
        src: "/db/images/characters/people/hero.png",
        x: utils.withGrid(2),
        y: utils.withGrid(4),
        behaviorLoop: [
          { type: "stand", direction: "up" }
        ]
      },
      timmy: {
        type: "Person",
        x: utils.withGrid(5),
        y: utils.withGrid(5),
        src: "/db/images/characters/people/timmy.png",
        behaviorLoop: [
          { type: "stand", direction: "right", time: 1000 },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "up", time: 1000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "stand", direction: "down", time: 1000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "up", time: 1000 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
        ],
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "TIMMY: Sorry, I'm busy!",
                faceHero: "timmy",
              },
            ],
          },
        ],
      },
      mouse: {
        type: "Person",
        x: utils.withGrid(2),
        y: utils.withGrid(7),
        src: "/db/images/characters/people/mouse.png",
        behaviorLoop: [
          { type: "stand", direction: "right" }
        ],
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "MOUSE: Ahahaaaaaaa",
                faceHero: "mouse",
              },
            ],
          },
        ],
      },
      cypher: {
        type: "Person",
        x: utils.withGrid(9),
        y: utils.withGrid(10),
        src: "/db/images/characters/people/cypher.png",
        behaviorLoop: [
          { type: "stand", direction: "left" }
        ],
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Cypher: Ahahaaaaaaa",
                faceHero: "cypher",
              },
            ],
          },
        ],
      },
      regina: {
        type: "Person",
        x: utils.withGrid(10),
        y: utils.withGrid(5),
        src: "/db/images/characters/people/regina.png",
        behaviorLoop: [
          { type: "stand", direction: "right" }
        ],
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Regina: Ahahaaaaaaa",
                faceHero: "regina",
              },
            ],
          },
        ],
      },
    },
    walls: {
      [utils.asGridCoord(1, 3)]: true,
      [utils.asGridCoord(2, 3)]: true,
      [utils.asGridCoord(3, 3)]: true,
      [utils.asGridCoord(4, 3)]: true,
      [utils.asGridCoord(5, 3)]: true,
      [utils.asGridCoord(6, 3)]: true,
      [utils.asGridCoord(7, 2)]: true,
      [utils.asGridCoord(8, 3)]: true,
      [utils.asGridCoord(9, 4)]: true,
      [utils.asGridCoord(10, 4)]: true,
      [utils.asGridCoord(11, 4)]: true,
      [utils.asGridCoord(12, 4)]: true,
      [utils.asGridCoord(0, 4)]: true,
      [utils.asGridCoord(0, 5)]: true,
      [utils.asGridCoord(0, 6)]: true,
      [utils.asGridCoord(0, 7)]: true,
      [utils.asGridCoord(0, 8)]: true,
      [utils.asGridCoord(0, 9)]: true,
      [utils.asGridCoord(0, 10)]: true,
      [utils.asGridCoord(0, 11)]: true,
      [utils.asGridCoord(13, 5)]: true,
      [utils.asGridCoord(13, 6)]: true,
      [utils.asGridCoord(13, 7)]: true,
      [utils.asGridCoord(13, 8)]: true,
      [utils.asGridCoord(13, 9)]: true,
      [utils.asGridCoord(13, 10)]: true,
      [utils.asGridCoord(13, 11)]: true,
      [utils.asGridCoord(1, 12)]: true,
      [utils.asGridCoord(2, 12)]: true,
      [utils.asGridCoord(3, 12)]: true,
      [utils.asGridCoord(4, 12)]: true,
      [utils.asGridCoord(5, 12)]: true,
      [utils.asGridCoord(6, 13)]: true,
      [utils.asGridCoord(7, 12)]: true,
      [utils.asGridCoord(8, 12)]: true,
      [utils.asGridCoord(9, 12)]: true,
      [utils.asGridCoord(10, 12)]: true,
      [utils.asGridCoord(11, 12)]: true,
      [utils.asGridCoord(12, 12)]: true,
      [utils.asGridCoord(6, 4)]: true,
      [utils.asGridCoord(6, 5)]: true,
      [utils.asGridCoord(1, 5)]: true,
      [utils.asGridCoord(2, 5)]: true,
      [utils.asGridCoord(3, 5)]: true,
      [utils.asGridCoord(4, 5)]: true,
      [utils.asGridCoord(3, 7)]: true,
      [utils.asGridCoord(3, 10)]: true,
      [utils.asGridCoord(8, 7)]: true,
      [utils.asGridCoord(8, 10)]: true,
      [utils.asGridCoord(11, 5)]: true,
      [utils.asGridCoord(11, 7)]: true,
      [utils.asGridCoord(12, 7)]: true,
    },
    cutsceneSpaces: {
      [utils.asGridCoord(7, 3)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "Kitchen",
              x: utils.withGrid(5),
              y: utils.withGrid(10),
              direction: "up",
            },
          ],
        },
      ],
      [utils.asGridCoord(6, 12)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "Street",
              x: utils.withGrid(5),
              y: utils.withGrid(9),
              direction: "down",
            },
          ],
        },
      ],
    },
  },
  Kitchen: {
    id: "Kitchen",
    lowerSrc: "/db/images/maps/KitchenLower.png",
    upperSrc: "/db/images/maps/KitchenUpper.png",
    configObjects: {
      hero: {
        type: "Person",
        isPlayerControlled: true,
        x: utils.withGrid(5),
        y: utils.withGrid(9),
      },
      lavender: {
        type: "Person",
        x: utils.withGrid(9),
        y: utils.withGrid(6),
        src: "/db/images/characters/people/lavender.png",
        behaviorLoop: [
          { type: "stand", direction: "down", time: 1500 },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "down", time: 2000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "stand", direction: "up", time: 1000 },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "up", time: 1000 },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "down", time: 2000 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" }
        ],
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "lavender: You made it!",
                faceHero: "lavender",
              },
            ],
          },
        ],
      },
      eligor: {
        type: "Person",
        x: utils.withGrid(2),
        y: utils.withGrid(7),
        src: "/db/images/characters/people/eligor.png",
        behaviorLoop: [
          { type: "stand", direction: "left", time: 2000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "down", time: 1000 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "left", time: 2000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "down", time: 1000 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "left", time: 2000 },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" }
        ],
      },
      kenji: {
        type: "Person",
        x: utils.withGrid(6),
        y: utils.withGrid(4),
        src: "/db/images/characters/people/kenji.png",
        behaviorLoop: [
          { type: "stand", direction: "up", time: 3000 },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "up", time: 3000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "up", time: 3000 },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "up", time: 3000 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "up", time: 3000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" }
        ],
      },
    },
    walls: {
      [utils.asGridCoord(1, 3)]: true,
      [utils.asGridCoord(2, 3)]: true,
      [utils.asGridCoord(3, 3)]: true,
      [utils.asGridCoord(4, 3)]: true,
      [utils.asGridCoord(5, 3)]: true,
      [utils.asGridCoord(6, 3)]: true,
      [utils.asGridCoord(7, 3)]: true,
      [utils.asGridCoord(8, 3)]: true,
      [utils.asGridCoord(9, 3)]: true,
      [utils.asGridCoord(10, 3)]: true,
      [utils.asGridCoord(11, 4)]: true,
      [utils.asGridCoord(12, 4)]: true,
      [utils.asGridCoord(1, 5)]: true,
      [utils.asGridCoord(1, 6)]: true,
      [utils.asGridCoord(1, 7)]: true,
      [utils.asGridCoord(0, 4)]: true,
      [utils.asGridCoord(0, 8)]: true,
      [utils.asGridCoord(1, 9)]: true,
      [utils.asGridCoord(2, 9)]: true,
      [utils.asGridCoord(3, 10)]: true,
      [utils.asGridCoord(4, 10)]: true,
      [utils.asGridCoord(5, 11)]: true,
      [utils.asGridCoord(6, 10)]: true,
      [utils.asGridCoord(7, 10)]: true,
      [utils.asGridCoord(8, 10)]: true,
      [utils.asGridCoord(9, 10)]: true,
      [utils.asGridCoord(10, 10)]: true,
      [utils.asGridCoord(11, 10)]: true,
      [utils.asGridCoord(12, 10)]: true,
      [utils.asGridCoord(13, 9)]: true,
      [utils.asGridCoord(13, 8)]: true,
      [utils.asGridCoord(13, 7)]: true,
      [utils.asGridCoord(13, 6)]: true,
      [utils.asGridCoord(13, 5)]: true,
      [utils.asGridCoord(6, 7)]: true,
      [utils.asGridCoord(7, 7)]: true,
      [utils.asGridCoord(9, 7)]: true,
      [utils.asGridCoord(10, 7)]: true,
      [utils.asGridCoord(9, 9)]: true,
      [utils.asGridCoord(10, 9)]: true,
    },
    cutsceneSpaces: {
      [utils.asGridCoord(5, 10)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "Tony",
              x: utils.withGrid(7),
              y: utils.withGrid(3),
              direction: "down",
            },
          ],
        },
      ],
    },
  },
  Shop: {
    id: "Shop",
    lowerSrc: "/db/images/maps/PizzaShopLower.png",
    upperSrc: "/db/images/maps/PizzaShopUpper.png",
    configObjects: {
      hero: {
        type: "Person",
        isPlayerControlled: true,
        x: utils.withGrid(5),
        y: utils.withGrid(10),
      },
      cypher: {
        type: "Person",
        x: utils.withGrid(3),
        y: utils.withGrid(5),
        src: "/db/images/characters/people/cypher.png",
        behaviorLoop: [
          { type: "stand", direction: "down", time: 5000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "stand", direction: "up", time: 3000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "right", time: 3000 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
        ],
      },
      mouse: {
        type: "Person",
        x: utils.withGrid(9),
        y: utils.withGrid(8),
        src: "/db/images/characters/people/mouse.png",
        behaviorLoop: [
          { type: "stand", direction: "left" }
        ],
      }
    },
    walls: {
      [utils.asGridCoord(1, 3)]: true,
      [utils.asGridCoord(3, 3)]: true,
      [utils.asGridCoord(4, 3)]: true,
      [utils.asGridCoord(5, 3)]: true,
      [utils.asGridCoord(6, 3)]: true,
      [utils.asGridCoord(7, 3)]: true,
      [utils.asGridCoord(8, 3)]: true,
      [utils.asGridCoord(10, 3)]: true,
      [utils.asGridCoord(0, 4)]: true,
      [utils.asGridCoord(0, 5)]: true,
      [utils.asGridCoord(0, 6)]: true,
      [utils.asGridCoord(0, 7)]: true,
      [utils.asGridCoord(0, 8)]: true,
      [utils.asGridCoord(0, 9)]: true,
      [utils.asGridCoord(0, 10)]: true,
      [utils.asGridCoord(0, 11)]: true,
      [utils.asGridCoord(11, 4)]: true,
      [utils.asGridCoord(11, 5)]: true,
      [utils.asGridCoord(11, 6)]: true,
      [utils.asGridCoord(11, 7)]: true,
      [utils.asGridCoord(11, 8)]: true,
      [utils.asGridCoord(11, 9)]: true,
      [utils.asGridCoord(11, 10)]: true,
      [utils.asGridCoord(11, 11)]: true,
      [utils.asGridCoord(1, 12)]: true,
      [utils.asGridCoord(2, 12)]: true,
      [utils.asGridCoord(3, 12)]: true,
      [utils.asGridCoord(4, 12)]: true,
      [utils.asGridCoord(5, 13)]: true,
      [utils.asGridCoord(6, 12)]: true,
      [utils.asGridCoord(7, 12)]: true,
      [utils.asGridCoord(8, 12)]: true,
      [utils.asGridCoord(9, 12)]: true,
      [utils.asGridCoord(10, 12)]: true,
      [utils.asGridCoord(3, 8)]: true,
      [utils.asGridCoord(3, 9)]: true,
      [utils.asGridCoord(3, 10)]: true,
      [utils.asGridCoord(4, 8)]: true,
      [utils.asGridCoord(4, 9)]: true,
      [utils.asGridCoord(4, 10)]: true,
      [utils.asGridCoord(7, 8)]: true,
      [utils.asGridCoord(7, 9)]: true,
      [utils.asGridCoord(8, 8)]: true,
      [utils.asGridCoord(8, 9)]: true,
      [utils.asGridCoord(7, 6)]: true,
      [utils.asGridCoord(8, 6)]: true,
      [utils.asGridCoord(9, 6)]: true,
      [utils.asGridCoord(9, 5)]: true,
      [utils.asGridCoord(9, 4)]: true,
      [utils.asGridCoord(2, 4)]: true,
      [utils.asGridCoord(2, 5)]: true,
      [utils.asGridCoord(2, 6)]: true,
      [utils.asGridCoord(3, 6)]: true,
      [utils.asGridCoord(4, 6)]: true,
      [utils.asGridCoord(5, 6)]: true,
    },
    cutsceneSpaces: {
      [utils.asGridCoord(5, 12)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "Street",
              x: utils.withGrid(29),
              y: utils.withGrid(9),
              direction: "down",
            },
          ],
        },
      ],
    },
  },
  North: {
    id: "North",
    lowerSrc: "/db/images/maps/StreetNorthLower.png",
    upperSrc: "/db/images/maps/StreetNorthUpper.png",
    configObjects: {
      hero: {
        type: "Person",
        isPlayerControlled: true,
        x: utils.withGrid(5),
        y: utils.withGrid(8),
      },
      mouse: {
        type: "Person",
        x: utils.withGrid(8),
        y: utils.withGrid(12),
        src: "/db/images/characters/people/mouse.png",
        behaviorLoop: [
          { type: "stand", direction: "down", time: 2000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "down", time: 5000 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" }
        ],
      }
    },
    walls: {
      [utils.asGridCoord(1, 8)]: true,
      [utils.asGridCoord(1, 9)]: true,
      [utils.asGridCoord(1, 10)]: true,
      [utils.asGridCoord(1, 11)]: true,
      [utils.asGridCoord(1, 12)]: true,
      [utils.asGridCoord(1, 13)]: true,
      [utils.asGridCoord(1, 14)]: true,
      [utils.asGridCoord(2, 15)]: true,
      [utils.asGridCoord(3, 15)]: true,
      [utils.asGridCoord(4, 15)]: true,
      [utils.asGridCoord(5, 15)]: true,
      [utils.asGridCoord(6, 15)]: true,
      [utils.asGridCoord(6, 16)]: true,
      [utils.asGridCoord(7, 17)]: true,
      [utils.asGridCoord(8, 16)]: true,
      [utils.asGridCoord(8, 15)]: true,
      [utils.asGridCoord(9, 15)]: true,
      [utils.asGridCoord(10, 15)]: true,
      [utils.asGridCoord(11, 15)]: true,
      [utils.asGridCoord(12, 15)]: true,
      [utils.asGridCoord(13, 15)]: true,
      [utils.asGridCoord(14, 14)]: true,
      [utils.asGridCoord(14, 13)]: true,
      [utils.asGridCoord(14, 12)]: true,
      [utils.asGridCoord(14, 11)]: true,
      [utils.asGridCoord(14, 10)]: true,
      [utils.asGridCoord(14, 9)]: true,
      [utils.asGridCoord(14, 8)]: true,
      [utils.asGridCoord(14, 7)]: true,
      [utils.asGridCoord(13, 6)]: true,
      [utils.asGridCoord(12, 6)]: true,
      [utils.asGridCoord(11, 6)]: true,
      [utils.asGridCoord(10, 5)]: true,
      [utils.asGridCoord(9, 5)]: true,
      [utils.asGridCoord(8, 5)]: true,
      [utils.asGridCoord(7, 4)]: true,
      [utils.asGridCoord(6, 5)]: true,
      [utils.asGridCoord(5, 5)]: true,
      [utils.asGridCoord(4, 5)]: true,
      [utils.asGridCoord(3, 6)]: true,
      [utils.asGridCoord(3, 7)]: true,
      [utils.asGridCoord(2, 7)]: true,
      [utils.asGridCoord(7, 8)]: true,
      [utils.asGridCoord(7, 9)]: true,
      [utils.asGridCoord(7, 10)]: true,
      [utils.asGridCoord(8, 8)]: true,
      [utils.asGridCoord(8, 9)]: true,
      [utils.asGridCoord(8, 10)]: true,
      [utils.asGridCoord(9, 10)]: true,
      [utils.asGridCoord(10, 10)]: true,
    },
    cutsceneSpaces: {
      [utils.asGridCoord(7, 16)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "Street",
              x: utils.withGrid(25),
              y: utils.withGrid(5),
              direction: "down",
            },
          ],
        },
      ],
      [utils.asGridCoord(7, 5)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "Green",
              x: utils.withGrid(5),
              y: utils.withGrid(12),
              direction: "up",
            },
          ],
        },
      ],
    },
  },
  Green: {
    id: "Green",
    lowerSrc: "/db/images/maps/GreenKitchenLower.png",
    upperSrc: "/db/images/maps/GreenKitchenUpper.png",
    configObjects: {
      hero: {
        type: "Person",
        isPlayerControlled: true,
        x: utils.withGrid(5),
        y: utils.withGrid(10),
      },
      ironChef: {
        type: "Person",
        x: utils.withGrid(4),
        y: utils.withGrid(4),
        src: "/db/images/characters/people/ironChef.png",
        behaviorLoop: [
          { type: "stand", direction: "up", time: 2000 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "up", time: 2000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "up", time: 2000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "up", time: 2000 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" }
        ],
      },
      regina: {
        type: "Person",
        x: utils.withGrid(8),
        y: utils.withGrid(9),
        src: "/db/images/characters/people/regina.png",
        behaviorLoop: [
          { type: "stand", direction: "down", time: 1500 },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "stand", direction: "up", time: 1500 },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "stand", direction: "up", time: 1500 },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" }
        ],
      },
      timmy: {
        type: "Person",
        x: utils.withGrid(3),
        y: utils.withGrid(7),
        src: "/db/images/characters/people/timmy.png",
        behaviorLoop: [
          { type: "stand", direction: "up" }
        ],
      },
      johnny: {
        type: "Person",
        x: utils.withGrid(7),
        y: utils.withGrid(10),
        src: "/db/images/characters/people/johnny.png",
        behaviorLoop: [
          { type: "stand", direction: "right" }
        ],
      },
    },
    walls: {
      [utils.asGridCoord(0, 4)]: true,
      [utils.asGridCoord(0, 5)]: true,
      [utils.asGridCoord(1, 6)]: true,
      [utils.asGridCoord(2, 6)]: true,
      [utils.asGridCoord(3, 6)]: true,
      [utils.asGridCoord(4, 6)]: true,
      [utils.asGridCoord(5, 6)]: true,
      [utils.asGridCoord(6, 6)]: true,
      [utils.asGridCoord(0, 7)]: true,
      [utils.asGridCoord(0, 8)]: true,
      [utils.asGridCoord(0, 9)]: true,
      [utils.asGridCoord(0, 10)]: true,
      [utils.asGridCoord(0, 11)]: true,
      [utils.asGridCoord(10, 5)]: true,
      [utils.asGridCoord(10, 6)]: true,
      [utils.asGridCoord(10, 7)]: true,
      [utils.asGridCoord(10, 8)]: true,
      [utils.asGridCoord(10, 9)]: true,
      [utils.asGridCoord(10, 10)]: true,
      [utils.asGridCoord(10, 11)]: true,
      [utils.asGridCoord(1, 12)]: true,
      [utils.asGridCoord(2, 12)]: true,
      [utils.asGridCoord(3, 12)]: true,
      [utils.asGridCoord(4, 12)]: true,
      [utils.asGridCoord(5, 13)]: true,
      [utils.asGridCoord(6, 12)]: true,
      [utils.asGridCoord(7, 12)]: true,
      [utils.asGridCoord(8, 12)]: true,
      [utils.asGridCoord(9, 12)]: true,
      [utils.asGridCoord(1, 3)]: true,
      [utils.asGridCoord(2, 3)]: true,
      [utils.asGridCoord(3, 3)]: true,
      [utils.asGridCoord(4, 3)]: true,
      [utils.asGridCoord(5, 3)]: true,
      [utils.asGridCoord(6, 3)]: true,
      [utils.asGridCoord(7, 3)]: true,
      [utils.asGridCoord(8, 4)]: true,
      [utils.asGridCoord(9, 4)]: true,
      [utils.asGridCoord(3, 9)]: true,
      [utils.asGridCoord(8, 10)]: true,
    },
    cutsceneSpaces: {
      [utils.asGridCoord(5, 12)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "North",
              x: utils.withGrid(7),
              y: utils.withGrid(5),
              direction: "down",
            },
          ],
        },
      ],
    },
  },
}
